### ISSUE TITLE
Django constance - widok tabelki

### ISSUE THREAD

**Issue by mik-laj** [watchdogpolska/prezydent.siecobywatelska.pl#11]
Aktualnie strona nie potrafi wykorzystać powierzchni ekranu. Pole textarea jest strasznie małe, a jest tam najwięcej miejsca
pics related http://imgur.com/5JV2mrb?tags

Proponowany kod CSS, który poprawi poniżej.
Da to efekt: http://imgur.com/W2aWbYd

``` css
#result_list{
  table-layout: fixed;
}
#result_list > thead:nth-child(1) > tr:nth-child(1) > th:nth-child(1){
  width: 10%;
}
#result_list > thead:nth-child(1) > tr:nth-child(1) > th:nth-child(2){
  width: 30%;
}
#result_list > thead:nth-child(1) > tr:nth-child(1) > th:nth-child(3){
  width: 60%;
}
#result_list > thead:nth-child(1) > tr:nth-child(1) > th:nth-child(4){
  width: 20px;
}

#result_list > tbody:nth-child(2) > tr > td:nth-child(3)  textarea{
  width: 100%;
  height: 300px
}
```
